const products = [
  {
    id: 1,
    name: "Premium Classic Watch",
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d",
    price: 1590,
    oldPrice: 1990,
    discount: 20,
    rating: 4.8,
    sold: 128,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "A premium classic watch with an elegant design.",
    downloadUrl: "",
    downloadLabel: ""
  },

  {
    id: 2,
    name: "Elegant Premium Watch",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
    price: 1890,
    oldPrice: 2390,
    discount: 21,
    rating: 4.9,
    sold: 96,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "Elegant premium watch suitable for everyday and formal use.",
    downloadUrl: "",
    downloadLabel: ""
  },

  {
    id: 3,
    name: "Classic Leather Watch",
    image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade",
    price: 1490,
    oldPrice: 1890,
    discount: 21,
    rating: 4.7,
    sold: 84,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "Classic leather strap watch with a premium appearance.",
    downloadUrl: "",
    downloadLabel: ""
  },

  {
    id: 4,
    name: "Premium Dark Chocolate",
    image: "https://images.unsplash.com/photo-1575377427642-087cf684f29d",
    price: 590,
    oldPrice: 690,
    discount: 14,
    rating: 4.8,
    sold: 142,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "Premium dark chocolate made for chocolate lovers.",
    downloadUrl: "",
    downloadLabel: ""
  },

  {
    id: 5,
    name: "Luxury Chocolate Gift Box",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b",
    price: 890,
    oldPrice: 1090,
    discount: 18,
    rating: 4.9,
    sold: 76,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "A luxury chocolate gift box for special occasions.",
    downloadUrl: "",
    downloadLabel: ""
  },

  {
    id: 6,
    name: "Premium Digital Book",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f",
    price: 490,
    oldPrice: 690,
    discount: 29,
    rating: 4.8,
    sold: 61,
    productType: "digital",
    free: false,
    offerAvailable: true,
    available: true,
    description: "A premium digital book available after successful payment.",
    downloadUrl: "downloads/premium-digital-book.pdf",
    downloadLabel: "Download Book"
  },

  {
    id: 7,
    name: "Special Selection Watch",
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49",
    price: 1680,
    oldPrice: 1990,
    discount: 16,
    rating: 4.8,
    sold: 73,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "Special selection premium watch with modern styling.",
    downloadUrl: "",
    downloadLabel: ""
  },

  {
    id: 8,
    name: "Premium Gift Collection",
    image: "https://images.unsplash.com/photo-1512909006721-3d6018887383",
    price: 1290,
    oldPrice: 1590,
    discount: 19,
    rating: 4.7,
    sold: 54,
    productType: "physical",
    free: false,
    offerAvailable: true,
    available: true,
    description: "A premium gift collection for your loved ones.",
    downloadUrl: "",
    downloadLabel: ""
  },

  // PAID DIGITAL PRODUCT
  {
    id: 9,
    name: "Premium Success Guide",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794",
    price: 390,
    oldPrice: 590,
    discount: 34,
    rating: 4.9,
    sold: 32,
    productType: "digital",
    free: false,
    offerAvailable: true,
    available: true,
    description: "A premium digital guide. Payment is required before download.",
    downloadUrl: "downloads/premium-success-guide.pdf",
    downloadLabel: "Download Book"
  },

  // FREE DIGITAL PRODUCT
  {
    id: 10,
    name: "Free Starter Guide",
    image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d",
    price: 0,
    oldPrice: 0,
    discount: 0,
    rating: 4.9,
    sold: 120,
    productType: "digital",
    free: true,
    offerAvailable: false,
    available: true,
    description: "A free digital starter guide for our customers.",
    downloadUrl: "downloads/free-starter-guide.pdf",
    downloadLabel: "Download Free Book"
  }
];